### ISSUE TITLE
idbrii/vim-mark

### ISSUE THREAD

**Issue by idbrii** [mikedfunk/dotfiles#2]
Searching github (for something else) I saw your vimrc:

```
" fork that is maintained... but it conflicts with a mapping i have and
" doesn't work
" Plug 'idbrii/vim-mark'
```

https://github.com/mikedfunk/dotfiles/blob/9fb3af52e6405267fc4adac05df2f56c5aac1141/to_link/vim/.vimrc.plugins#L724-L726

Forgive my intrusion, but if you 

```
let g:mark_no_mappings = 1
```

then my fork of vim-mark will not make any mappings (that's why I forked). Then you can

```
map <unique> <Leader>m <Plug>MarkSet
```

to set your own map.

HTH

**Comment by mikedfunk** [comment]
Ok, but now when I install your plugin, set `let g:mark_no_mappings = 1` and call `:Mark` I get "All Marks Disabled". I can't seem to mark anything.

**Comment by idbrii** [comment]
You have to use `:Mark <pattern>` or a map to set a mark.
Example for this text: `:Mark to` will highlight three words.

-David

**Comment by mikedfunk** [comment]
Oh ok. Is there no command to mark the word under the cursor?

**Comment by idbrii** [comment]
No, I don't believe so. I guess because technically once you're at the
cmdline entering the command, your cursor is no longer under the word. (Not
that it's impossible to do what you want, just that it was assumed that it
wouldn't be a common use case.)

Unfortunately, I'm not sure how best to do what you want.

Some thing like `:command! MarkThis execute "Mark ". expand('<cword>')` is
probably close. (Execute is necessary to evaluate expand().)

However, that's duplicating Mark's internal logic of defining a word (maybe
it does the same thing -- I haven't looked).

-David
